[project]
name = "cn-holiday-email"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.6.4",
    "httpx>=0.28.1",
    "openai>=1.91.0",
    "pycountry>=24.6.1",
    "python-dotenv>=1.1.1",
]
